"""init

Revision ID: 67709bef28f0
Revises: b6f49d5630bc
Create Date: 2026-09-15 21:13:12.722380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67709bef28f0'
down_revision = 'b6f49d5630bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_usuario', schema=None) as batch_op:
        batch_op.alter_column('acepto_habeas_data',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_usuario', schema=None) as batch_op:
        batch_op.alter_column('acepto_habeas_data',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###
