"""init

Revision ID: 90281acd11d6
Revises: 
Create Date: 2026-08-21 01:39:09.849738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90281acd11d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_restante', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('umbral_alerta', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.drop_column('umbral_alerta')
        batch_op.drop_column('cantidad_restante')

    # ### end Alembic commands ###
