"""init

Revision ID: b6f49d5630bc
Revises: 90281acd11d6
Create Date: 2026-09-15 17:43:11.676657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f49d5630bc'
down_revision = '90281acd11d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_usuario', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=25),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_usuario', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
